export const memberShipPlanData: any = [
  {
    id: 1,
    name: "Single Child Membership Monthly Payment",
    plan_value: "a",
    plan_price: "$83.25",
    plan_type: "single_child",
    plan_price_text: "$83.25/month",
    plan_text: "$83.25/month (plus applicable taxes) after your trial",
  },
  {
    id: 2,
    name: "Single Child Annual Payment",
    plan_value: "b",
    plan_price: "$747.00",
    plan_type: "single_child",
    plan_price_text: "$747.00/year",
    plan_text: "$747.00/year (plus applicable taxes) after your trial",
  },
  {
    id: 3,
    name: "Single Child Lifetime Payment",
    plan_value: "c",
    plan_price: "$1,997.00",
    plan_type: "single_child",
    plan_price_text: "$1,997.00 Lifetime",
    plan_text: "$1,997.00 Lifetime (plus applicable taxes) after your trial",
  },
  {
    id: 4,
    name: "Family Membership Monthly Payment",
    plan_value: "d",
    plan_price: "$108.25",
    plan_type: "family",
    plan_price_text: "$108.25/month",
    plan_text: "$108.25/month (plus applicable taxes) after your trial",
  },
  {
    id: 5,
    name: "Family Membership Annual Payment",
    plan_value: "e",
    plan_price: "$947.00",
    plan_type: "family",
    plan_price_text: "$947.00/year",
    plan_text: "$947.00/year (plus applicable taxes) after your trial",
  },
  {
    id: 6,
    name: "Family Membership Lifetime Payment",
    plan_value: "f",
    plan_price: "$2,397.00",
    plan_type: "family",
    plan_price_text: "$2,397.00 Liftime",
    plan_text: "$2,397.00 Liftime (plus applicable taxes) after your trial",
  },
];
